server:
  port: 1001



spring:
  application:
    name: nacos-order-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost #nacos集群，使用的是域名

management:
  endpoints:
    web:
      exposure:
        include: '*'