server:
  port: 1002



spring:
  application:
    name: nacos-order-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost

management:
  endpoints:
    web:
      exposure:
        include: '*'