server:
  port: 8181



spring:
  application:
    # 应用名称
    name: cloudalibaba-sentinel-service
  cloud:
    #配置sentinel
    sentinel:
      transport:
        #配置sentinel dashboard地址
        dashboard: localhost:8080
        port: 8719 #默认8719端口


management:
  endpoints:
    web:
      exposure:
        include: '*'

