server:
  port: 7001


spring:
  application:
    name: nacos-user-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost #nacos集群，使用的是域名
    sentinel:
      transport:
        #配置sentinel dashboard地址
        dashboard: localhost:8080
        port: 8719 #默认8719端口

#消费者将要去访问微服务名称
service-url:
  nacos-order-service: http://nacos-order-provider
