server:
  port: 7005



spring:
  application:
    name: cloudalibaba-sentinel-gateway
  cloud:
    nacos:
      discovery:
        #nacos服务注册中心地址
        server-addr: localhost
    sentinel:
      transport:
        #配置sentinel dashboard地址
        dashboard: localhost:8080
        port: 8719 #默认8719端口
      datasource:
        flow:
          nacos:
            server-addr: localhost:8848
            dataId: ${spring.application.name}-flow-rules
            groupid: DEFAULT_GROUP
            data-type: json
            rule-type: flow
        gw-flow:
          nacos:
            server-addr: localhost:8848
            dataId: ${spring.application.name}-gw-flow-rules
            groupid: DEFAULT_GROUP
            data-type: json
            rule-type: gw-flow
        gw-api-group:
          nacos:
            server-addr: localhost:8848
            dataId: ${spring.application.name}-gw-api-group-rules
            groupid: DEFAULT_GROUP
            data-type: json
            rule-type: gw-api-group

#      scg:  #配置限流之后，自定义响应内容
#        fallback:
#          mode: response
#          response-status: 426
#          response-body: 限流了
    gateway:
      routes:
        - id: order_routh  #路由的ID，没有固定规则但要求唯一，建议配合服务名
            #          uri: http://localhost:1001 #单个实例，匹配后提供服务的路由地址 （启动，cloudalibaba-provider-order1001服务）
          uri: lb://nacos-order-provider #使用nacos作为注册中心，匹配后提供服务的路由地址（集群实例配置方式）
          predicates:
            - Path=/order/** #断言，路径相匹配的进行路由


management:
  endpoints:
    web:
      exposure:
        include: '*'

