server:
  port: 7002



spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost
    sentinel:
      transport:
        #配置sentinel dashboard地址
        dashboard: localhost:8080
        port: 8719 #默认8719端口

#消费者将要去访问微服务名称
service-url:
  nacos-user-service: http://nacos-order-provider

#激活sentinel对feign支持
feign:
  sentinel:
    enabled: true
