server:
  port: 9094



spring:
  application:
    name: cloudalibaba-sentinel-cluster-client-alone
  cloud:
    sentinel:
      transport:
        #配置sentinel dashboard地址
        dashboard: localhost:8080
        port: 8720 #默认8719端口


