server:
  port: 9092



spring:
  application:
    name: cloudalibaba-sentinel-cluster-server-alone
  cloud:
    sentinel:
      transport:
        #配置sentinel dashboard地址
        dashboard: localhost:8080
        port: 8719 #默认8719端口


